language: android
jdk: oraclejdk8

# 开启基于容器的Travis CI任务，让编译效率更高
# sudo: false
sudo: required

install: true


before_script:
  - chmod +x gradlew

android:
  components:
    # 构建项目所用的BuildTools版本
    - build-tools-30.0.3
    # 用来编译项目的SDK版本
    - android-29

    # 添加Android Support Repository组件
    - extra-android-m2repository
    # 添加Support Library组件
    - extra-android-support


script:
  - ./gradlew assembleRelease --stacktrace
